apiVersion: v1
kind: Secret
metadata:
  name: devops-platform-secret
  namespace: devops-platform
type: Opaque
stringData:
  DATABASE_PASSWORD: "REPLACE_WITH_DATABASE_PASSWORD"
  POSTGRES_PASSWORD: "REPLACE_WITH_DATABASE_PASSWORD"
